### ISSUE TITLE
let's get rid of synchronize

### ISSUE THREAD

**Issue by yegor256** [yegor256/random-port#3]
This is what I see:

```
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/random-port-0.2.0/lib/random-port/pool.rb:42:in `synchronize'
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/random-port-0.2.0/lib/random-port/pool.rb:42:in `acquire'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`
