### ISSUE TITLE
Can't find a place in the pool of 65536 ports...

### ISSUE THREAD

**Issue by yegor256** [yegor256/random-port#40]
```
RandomPort::Pool::Timeout: Can't find a place in the pool of 65536 ports for 1 port(s), after 361639 attempts in 4s
            /Users/yb/.rvm/gems/ruby-3.3.5/gems/random-port-0.7.2/lib/random-port/pool.rb:92:in `block in acquire'
            <internal:kernel>:187:in `loop'
            /Users/yb/.rvm/gems/ruby-3.3.5/gems/random-port-0.7.2/lib/random-port/pool.rb:90:in `acquire'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.4`
